name: beacon-nodejs
services:

  # will disappear and become a build step in the image production for hapi
  vue:
    image: "dept/beacon-nodejs"
    command: [ "vue" ]
    build: .
    networks: 
      beacon-v2-net:
        ipv4_address: 10.128.0.2

  hapi:
    image: "dept/beacon-nodejs"
    command: [ "hapi" ]
    build: .
    depends_on:
      - "mongodb"
    networks: 
      beacon-v2-net:
        ipv4_address: 10.128.0.3

  mongodb:
    image: "library/mongo"
    networks:
      beacon-v2-net:
          ipv4_address: 10.128.0.4

  vault:
    image: "hashicorp/vault"
    cap_add:
      - IPC_LOCK
    networks:
      beacon-v2-net:
        ipv4_address: 10.128.0.5

networks:
  beacon-v2-net:
    name: "beacon-v2-net"
    driver_opts: 
      com.docker.network.bridge.name: "beacon-v2-net"
    ipam:
      driver: default
      config:
        - subnet: "10.128.0.0/29"
